/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/": {
    /**
     * Retrieve Server
     * @description このGoverned Runnerの情報です。
     */
    get: operations["retrieve_server__get"];
  };
  "/users/me": {
    /** Retrieve Current User */
    get: operations["retrieve_current_user_users_me_get"];
  };
  "/jobs/": {
    /** Retrieve Jobs */
    get: operations["retrieve_jobs_jobs__get"];
    /** Create Job */
    post: operations["create_job_jobs__post"];
  };
  "/jobs/{job_id}": {
    /** Retrieve Job */
    get: operations["retrieve_job_jobs__job_id__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Body_create_job_jobs__post */
    Body_create_job_jobs__post: {
      /** File Url */
      file_url: string;
      /** @default run-crate */
      type?: components["schemas"]["FileType"];
      /**
       * Use Snapshot
       * @default false
       */
      use_snapshot?: boolean;
    };
    /**
     * FileType
     * @enum {string}
     */
    FileType: "run-crate" | "notebook";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** JobOut */
    JobOut: {
      /**
       * Id
       * @example JOB_ID
       */
      id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      status: components["schemas"]["State"] | null;
      source: components["schemas"]["SourceOut"] | null;
      result: components["schemas"]["ResultOut"] | null;
      progress: components["schemas"]["ProgressOut"] | null;
    };
    /** Page[JobOut] */
    Page_JobOut_: {
      /** Items */
      items: components["schemas"]["JobOut"][];
      /** Total */
      total: number | null;
      /** Page */
      page: number | null;
      /** Size */
      size: number | null;
      /** Pages */
      pages?: number | null;
    };
    /** ProgressOut */
    ProgressOut: {
      /** Url */
      url: string | null;
    };
    /** ResultOut */
    ResultOut: {
      /** Url */
      url: string | null;
    };
    /** ServerOut */
    ServerOut: {
      /**
       * Version
       * @example 0.0.1
       */
      version: string;
    };
    /** SourceOut */
    SourceOut: {
      /** Url */
      url: string | null;
    };
    /**
     * State
     * @enum {string}
     */
    State: "running" | "completed" | "failed";
    /** UserOut */
    UserOut: {
      /**
       * Id
       * @example 1
       */
      id: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Name */
      name: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Retrieve Server
   * @description このGoverned Runnerの情報です。
   */
  retrieve_server__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ServerOut"];
        };
      };
    };
  };
  /** Retrieve Current User */
  retrieve_current_user_users_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
    };
  };
  /** Retrieve Jobs */
  retrieve_jobs_jobs__get: {
    parameters: {
      query?: {
        state?: string | null;
        /** @description Page number */
        page?: number;
        /** @description Page size */
        size?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_JobOut_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Job */
  create_job_jobs__post: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_create_job_jobs__post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["JobOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Retrieve Job */
  retrieve_job_jobs__job_id__get: {
    parameters: {
      path: {
        job_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["JobOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
